id: strict-transport-security-checks
info: 
  name: Strict-Transport-Security Header Check
  author: Hamed Salimian, Arthur Bayart
  severity: low
  classification:
    cwe-id: CWE-523
  reference:
    - https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html
  tags: strict_transport_security,header,security,14.4.5
  description: |
    Based on ASVS 14.4.5 written by Hamed Salimian.
    Verify that a Strict-Transport-Security header with a minimum age of one year is included on all responses and for all subdomains, such as Strict-Transport-Security: max-age=15724800; includeSubdomains.
http:
  - global-matchers: true
    method: GET
    path: 
      - "{{ BaseURL }}"
    headers:
      User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.10 Safari/605.1.1"
      Accept: "*/*"
      Connection: close
      Host: "{{Hostname}}"
    extractors:
      - type: kval
        name: "Strict-Transport-Security"
        part: header
        kval:
          - Strict_Transport_Security
      - type: regex
        name: "max-age"
        part: header
        regex:
          - (?i)max-age=(\d+)
    stop-at-first-match: true
    matchers:
      - type: word
        name: "Strict-Transport-Security header does not exist"
        part: header
        negative: true
        words:
          - 'Strict-Transport-Security:'

      - type: regex
        name: "Strict-Transport-Security header does not include subdomains"
        part: header
        negative: true
        regex:
          - (?i)Strict-Transport-Security:\s*.*\bincludeSubdomains\b

      - type: dsl
        name: "Strict-Transport-Security header max-age is less than 1 years"
        dsl:
          - 'max_age < 31536000'